* Implement initial support for DEPS   - add libdraw package and fix build of dmenu * Support 'xz' compressed tarballs * make is now ${MAKE} and can be modified in 'config' file

diff --git a/slpm b/slpm
--- a/slpm
+++ b/slpm
@@ -19,6 +19,7 @@ ROOT="`dirname $ARG0`"
 USRDIR="${HOME}/.slpm"
 WRKDIR="${ROOT}/_work"
 PKGDIR="${ROOT}/pkg"
+MAKE=make
 . "${ROOT}/config"
 NFODIR="${DESTDIR}/${PREFIX}/var/lib/slpm/pkg"
 
@@ -75,6 +76,7 @@ tar_fetch() {
     case "$FILE" in
     *gz*) tar xzvf $FILE ; ;;
     *bz2*) tar xjvf $FILE ; ;;
+    *xz*) xz -d $FILE ; FILE2=`echo $FILE|sed -e s,.xz,,`; tar xvf $FILE2 ; ;;
     esac
   fi
 }
@@ -100,7 +102,7 @@ pkg_build() {
       ./configure "--prefix=${PREFIX}" ${CFGARGS} ${USER_CFGARGS}
     fi
   fi
-  make DESTDIR=${DESTDIR} PREFIX=${PREFIX} prefix=${PREFIX}
+  ${MAKE} DESTDIR=${DESTDIR} PREFIX=${PREFIX} prefix=${PREFIX}
 }
 
 pkg_install() {
@@ -127,7 +129,7 @@ pkg_register() {
   mkdir -p "${WRKDIR}/.tmp/${PKG}/bin"
   mkdir -p "${WRKDIR}/.tmp/${PKG}/lib"
   mkdir -p "${WRKDIR}/.tmp/${PKG}/man/man1"
-  ${PKGINSTALL} "DESTDIR=${WRKDIR}/.tmp/${PKG}" "prefix=${WRKDIR}/.tmp/${PKG}"
+  ${PKGINSTALL} PREFIX=/ "DESTDIR=${WRKDIR}/.tmp/${PKG}" "prefix=${WRKDIR}/.tmp/${PKG}"
   # go register
   cd "${WRKDIR}/.tmp/${PKG}"
   echo "${WRKDIR}/.tmp/${PKG}"
@@ -145,7 +147,7 @@ pkg_register() {
 
 pkg_clean() {
   cd "$WRKDIR/$PKG"
-  make clean
+  ${MAKE} clean
 }
 
 pkg_deinstall() {
@@ -158,7 +160,7 @@ pkg_deinstall() {
   else
     cd "$WRKDIR/$PKG"
 # TODO: wrap into ${PKGDEINSTALL}
-    make uninstall DESTDIR=${DESTDIR} PREFIX=${PREFIX}
+    ${MAKE} uninstall DESTDIR=${DESTDIR} PREFIX=${PREFIX}
   fi
 }
 
@@ -234,7 +236,7 @@ pkg_open() {
   CFGARGS=""
   BASEDIR=""
   INSTALL_POST="" # script to run after install
-  PKGINSTALL="make install"
+  PKGINSTALL="${MAKE} install"
   PKGINSTALL_ARGS="DESTDIR=${DESTDIR} PREFIX=${PREFIX} prefix=${PREFIX}"
   PKGCONFIGURE=""
   if [ ! -f "$PKGDIR/$PKG" ]; then
@@ -250,8 +252,12 @@ pkg_open() {
   if [ -z "${TYPE}" ]; then echo "No TYPE defined in package"; fi
   for DEP in ${DEPS}; do
     if [ ! -e "${NFODIR}/${DEP}" ]; then
-      echo "${PKG} depends on not yet installed ${DEP}"
-      exit 1
+      echo "=> Installing missing dependency.."
+      $0 -i ${DEP}
+      if [ ! $? = 0 ]; then
+        echo "=> Install of ${DEP} has failed"
+        exit 1
+      fi
     fi
   done
 }
