* Add new packages and update some others:   atk, gtk3.2, gmp, gc, dvtm, bash-4.2,   icecast, io, neko, mono, newlisp, proftpd,   rsync, reiserfstools, dash ..
--HG--
rename : pkg/bash-4.1 => pkg/bash-4.2
rename : pkg/dash-0.5.6 => pkg/dash-0.5.7
rename : pkg/gdk-pixbuf-2.22.1 => pkg/gdk-pixbuf-2.24.0
rename : pkg/gmp-5.0.1 => pkg/gmp-5.0.2
rename : pkg/gtk+-3.1.4 => pkg/gtk+-3.2.3
rename : pkg/rsync-3.0.7 => pkg/rsync-3.0.9

diff --git a/slpm b/slpm
--- a/slpm
+++ b/slpm
@@ -214,10 +214,10 @@ pkg_build() {
     else
       ${MAKE} ${MAKEFLAGS} DESTDIR=${DESTDIR} PREFIX=${PREFIX} prefix=${PREFIX} exec_prefix=${PREFIX}
     fi
-    if [ ! $? = 0 ]; then
-      echo "=> Make stage failed :("
-      exit 1
-    fi
+    #if [ ! $? = 0 ]; then
+    #  echo "=> Make stage failed :("
+    #  exit 1
+    #fi
     :> .slpm_build_done
   fi
 }
