* Detect directory existence in pkg_{build|install} * Fix sltar pkg * Add sup pkg * Fix possible error in make install

diff --git a/slpm b/slpm
--- a/slpm
+++ b/slpm
@@ -68,11 +68,19 @@ function pkg_update {
 }
 
 function pkg_build {
+  if [ ! -d "$WRKDIR/$PKG" ]; then
+    echo "pkg_build: Cannot open target directory"
+    exit 1
+  fi
   cd "$WRKDIR/$PKG"
   make "DESTDIR=${DESTDIR}" PREFIX=${PREFIX}
 }
 
 function pkg_install {
+  if [ ! -d "$WRKDIR/$PKG" ]; then
+    echo "pkg_install: Cannot open target directory"
+    exit 1
+  fi
   (
     cd "$WRKDIR/$PKG"
     make install DESTDIR=${DESTDIR} PREFIX=${PREFIX}
